name: dartpy
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0-133.0.dev <3.0.0"

dependencies:
  path: ^1.6.0
  ffi: any
  freezed_annotation: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  ffigen:
    path: ../../dev/ffigen
  freezed: any
# dependency_overrides:
#   ffigen:
#     git:
#       url: https://github.com/mannprerak2/ffigen.git
#       ref: dev-remove-no-sound-null-safety-flag
