name: dartpy
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: http://github.com/TimWhiting/dartpy

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  ffi: ^1.0.0
  freezed_annotation: ^0.14.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  ffigen: ^2.2.2
  freezed: ^0.14.0
  build_runner: ^1.11.5

