name: dartpy
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.9.0-1 <3.0.0"

dependencies:
  path: ^1.6.0
  ffi: any
  ffi_tool: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

dependency_overrides:
  ffi_tool:
    git:
      url: https://github.com/dart-interop/ffi_tool
