name: gendartpy_example
description: An example usage of gendartpy

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dartpy: any

dev_dependencies:
  gen_dartpy: any
  test: ^1.16.0
  build_runner: any

dependency_overrides:
  gen_dartpy:
    path: ../
  dartpy:
    path: ../../dartpy