name: gen_dartpy
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  source_gen: ^1.0.0
  dartpy: ^0.0.1+3

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8

dependency_overrides:
  dartpy:
    path: ../dartpy